# -*- coding: utf-8 -*-
"""4110E005

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7LWx_cTjLlH6Puh98PnvCJlOKyX75Ky
"""

x = 5

x <<= 3

print(x)

"""# 新增區段"""

x = 5

x **= 3

print(x)

"""# 新增區段"""

x = 10

x /= 2

print(x)

"""# 新增區段"""

x = 5

x &= 3

print(x)

"""# 新增區段"""

x = 2

print(x > 1 and x < 3)

"""# 新增區段"""

a = """This is 4110E005 speaking"""
print(a)

"""# 新增區段"""

a = '''123456789'''
print(a)

"""# 新增區段"""

b = "4110E005"
print(b[4:9])

"""# 新增區段"""

b = "0123456789"
print(b[:10])

"""# 新增區段"""

a = "abcdefg!"
print(a.upper())