# -*- coding: utf-8 -*-
"""4110E005

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7LWx_cTjLlH6Puh98PnvCJlOKyX75Ky
"""

x = 5

x <<= 3

print(x)

"""# 新增區段"""

x = 5

x **= 3

print(x)

"""# 新增區段"""

x = 10

x /= 2

print(x)

"""# 新增區段"""

x = 5

x &= 3

print(x)

"""# 新增區段"""

x = 2

print(x > 1 and x < 3)

"""# 新增區段"""

a = """This is 4110E005 speaking"""
print(a)

"""# 新增區段"""

a = '''123456789'''
print(a)

"""# 新增區段"""

b = "4110E005"
print(b[4:9])

"""# 新增區段"""

b = "0123456789"
print(b[:10])

"""# 新增區段"""

a = "abcdefg!"
print(a.upper())

"""# 新增區段"""

thislist = ["apple", "banana", "cherry"]
print(thislist[0])

"""# 新增區段"""

thislist = ["apple", "banana", "cherry"]
print(thislist[-3])

"""# 新增區段"""

thislist = ["A", "B", "C", "D", "E", "F", "G"]
print(thislist[4:7])

"""# 新增區段"""

thislist = ["apple", "banana", "cherry"]
thislist[1] = "B"

print(thislist)

"""# 新增區段"""

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
  if "a" in x:
    newlist.append(x)

print(newlist)

"""# 新增區段"""

thisdict =	{
  "A": "apple",
  "B": "banana",
  "C": "Cherry"
}
x = thisdict["A"]
print(x)

"""# 新增區段"""

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
for x in thisdict:
  print(thisdict[x])

"""# 新增區段"""

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

thisdict["year"] = 2022

print(thisdict)

"""# 新增區段"""

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.pop("year")
print(thisdict)

"""# 新增區段"""

thisdict = {
  "brand": "Brandy",
  "model": "whisky",
  "year": 2202
}
mydict = thisdict.copy()
print(mydict)