# -*- coding: utf-8 -*-
"""4110E005

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7LWx_cTjLlH6Puh98PnvCJlOKyX75Ky

1.
"""

x = 5

x <<= 3

print(x)

"""2."""

x = 5

x **= 3

print(x)

"""3."""

x = 10

x /= 2

print(x)

"""4."""

x = 5

x &= 3

print(x)

"""5."""

x = 2

print(x > 1 and x < 3)

"""6."""

a = """This is 4110E005 speaking"""
print(a)

"""7."""

a = '''123456789'''
print(a)

"""8."""

b = "4110E005"
print(b[4:9])

"""9."""

b = "0123456789"
print(b[:10])

"""10."""

a = "abcdefg!"
print(a.upper())

"""11."""

thislist = ["apple", "banana", "cherry"]
print(thislist[0])

"""12."""

thislist = ["apple", "banana", "cherry"]
print(thislist[-3])

"""13."""

thislist = ["A", "B", "C", "D", "E", "F", "G"]
print(thislist[4:7])

"""14."""

thislist = ["apple", "banana", "cherry"]
thislist[1] = "B"

print(thislist)

"""15."""

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
  if "a" in x:
    newlist.append(x)

print(newlist)

"""16."""

thisdict =	{
  "A": "apple",
  "B": "banana",
  "C": "Cherry"
}
x = thisdict["A"]
print(x)

"""17."""

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
for x in thisdict:
  print(thisdict[x])

"""18."""

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

thisdict["year"] = 2022

print(thisdict)

"""19."""

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.pop("year")
print(thisdict)

"""20."""

thisdict = {
  "brand": "Brandy",
  "model": "whisky",
  "year": 2202
}
mydict = thisdict.copy()
print(mydict)